<?php
/**
 * install.php - Complete Installation Wizard
 * PDF to Video Converter - Procedural PHP with MySQLi
 */

// Disable error display for security during installation
ini_set('display_errors', 0);
error_reporting(E_ALL);

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$errors = [];
$success = [];
$config_created = false;
$db_connected = false;
$tables_created = false;

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['action'])) {
        switch ($_POST['action']) {
            case 'check_requirements':
                // Check system requirements
                $requirements = [
                    'php_version' => version_compare(PHP_VERSION, '7.4', '>='),
                    'mysqli' => extension_loaded('mysqli'),
                    'gd' => extension_loaded('gd'),
                    'exec' => function_exists('exec'),
                    'ffmpeg' => false,
                    'espeak' => false,
                    'pdftotext' => false,
                ];
                
                // Check ffmpeg
                exec('which ffmpeg 2>/dev/null', $output, $return);
                $requirements['ffmpeg'] = ($return === 0);
                
                // Check espeak
                exec('which espeak 2>/dev/null', $output, $return);
                $requirements['espeak'] = ($return === 0);
                
                // Check pdftotext (poppler-utils)
                exec('which pdftotext 2>/dev/null', $output, $return);
                $requirements['pdftotext'] = ($return === 0);
                
                echo json_encode(['requirements' => $requirements]);
                exit;
                
            case 'test_db':
                $host = $_POST['db_host'] ?? 'localhost';
                $user = $_POST['db_user'] ?? '';
                $pass = $_POST['db_pass'] ?? '';
                $name = $_POST['db_name'] ?? '';
                
                if (empty($user) || empty($name)) {
                    echo json_encode(['success' => false, 'error' => 'Database username and name are required']);
                    exit;
                }
                
                $conn = @new mysqli($host, $user, $pass);
                
                if ($conn->connect_error) {
                    echo json_encode(['success' => false, 'error' => 'Connection failed: ' . $conn->connect_error]);
                    exit;
                }
                
                // Try to create database if it doesn't exist
                $conn->query("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                
                // Select the database
                $conn->select_db($name);
                
                if ($conn->error) {
                    echo json_encode(['success' => false, 'error' => 'Database selection failed: ' . $conn->error]);
                    exit;
                }
                
                $conn->close();
                echo json_encode(['success' => true, 'message' => 'Database connection successful!']);
                exit;
                
            case 'create_config':
                $host = $_POST['db_host'] ?? 'localhost';
                $user = $_POST['db_user'] ?? '';
                $pass = $_POST['db_pass'] ?? '';
                $name = $_POST['db_name'] ?? '';
                $base_url = $_POST['base_url'] ?? '';
                
                if (empty($user) || empty($name)) {
                    echo json_encode(['success' => false, 'error' => 'Database credentials are required']);
                    exit;
                }
                
                // Generate config file content
                $config_content = "<?php\n";
                $config_content .= "/**\n";
                $config_content .= " * Database Configuration\n";
                $config_content .= " * Auto-generated by install.php\n";
                $config_content .= " */\n\n";
                $config_content .= "define('DB_HOST', '" . addslashes($host) . "');\n";
                $config_content .= "define('DB_USER', '" . addslashes($user) . "');\n";
                $config_content .= "define('DB_PASS', '" . addslashes($pass) . "');\n";
                $config_content .= "define('DB_NAME', '" . addslashes($name) . "');\n";
                $config_content .= "define('BASE_URL', '" . addslashes($base_url) . "');\n";
                $config_content .= "\n";
                $config_content .= "// Create database connection\n";
                $config_content .= "\$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);\n";
                $config_content .= "\n";
                $config_content .= "// Check connection\n";
                $config_content .= "if (\$conn->connect_error) {\n";
                $config_content .= "    die(\"Connection failed: \" . \$conn->connect_error);\n";
                $config_content .= "}\n";
                $config_content .= "\n";
                $config_content .= "// Set charset\n";
                $config_content .= "\$conn->set_charset(\"utf8mb4\");\n";
                
                // Try to write config file
                $config_path = __DIR__ . '/includes/config.php';
                $config_dir = __DIR__ . '/includes';
                
                // Create includes directory if it doesn't exist
                if (!is_dir($config_dir)) {
                    mkdir($config_dir, 0755, true);
                }
                
                if (file_put_contents($config_path, $config_content)) {
                    echo json_encode(['success' => true, 'message' => 'Configuration file created successfully!']);
                } else {
                    echo json_encode(['success' => false, 'error' => 'Failed to write config file. Please check permissions.']);
                }
                exit;
                
            case 'create_tables':
                // Load config
                $config_path = __DIR__ . '/includes/config.php';
                if (!file_exists($config_path)) {
                    echo json_encode(['success' => false, 'error' => 'Configuration file not found. Please complete previous step.']);
                    exit;
                }
                
                require_once $config_path;
                
                // SQL to create tables
                $sql = "
                CREATE TABLE IF NOT EXISTS videos (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    description TEXT,
                    pdf_filename VARCHAR(255),
                    video_filename VARCHAR(255),
                    thumbnail_filename VARCHAR(255),
                    duration INT DEFAULT 0,
                    status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX(status),
                    INDEX(created_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                
                CREATE TABLE IF NOT EXISTS conversion_logs (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    video_id INT,
                    log_message TEXT,
                    log_type ENUM('info', 'warning', 'error') DEFAULT 'info',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE,
                    INDEX(video_id),
                    INDEX(created_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                ";
                
                // Execute SQL
                $queries = array_filter(array_map('trim', explode(';', $sql)));
                
                foreach ($queries as $query) {
                    if (!empty($query) && !$conn->query($query)) {
                        echo json_encode(['success' => false, 'error' => 'Table creation failed: ' . $conn->error]);
                        exit;
                    }
                }
                
                echo json_encode(['success' => true, 'message' => 'Database tables created successfully!']);
                exit;
        }
    }
}

// Get current URL for base URL detection
$current_url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']);
$base_url_suggested = rtrim($current_url, '/');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installation - PDF to Video Converter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 0;
        }
        .installer-container {
            max-width: 800px;
            margin: 0 auto;
        }
        .installer-card {
            background: white;
            border-radius: 15px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        .installer-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .installer-header h1 {
            font-size: 2rem;
            margin-bottom: 10px;
        }
        .step-indicator {
            display: flex;
            justify-content: space-between;
            padding: 20px 30px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        .step-item {
            display: flex;
            flex-direction: column;
            align-items: center;
            flex: 1;
            position: relative;
        }
        .step-item:not(:last-child)::after {
            content: '';
            position: absolute;
            top: 15px;
            left: 50%;
            width: 100%;
            height: 2px;
            background: #e9ecef;
            z-index: 1;
        }
        .step-item.active:not(:last-child)::after {
            background: #667eea;
        }
        .step-number {
            width: 30px;
            height: 30px;
            border-radius: 50%;
            background: #e9ecef;
            color: #6c757d;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            z-index: 2;
            position: relative;
        }
        .step-item.active .step-number {
            background: #667eea;
            color: white;
        }
        .step-item.completed .step-number {
            background: #28a745;
            color: white;
        }
        .step-label {
            font-size: 0.85rem;
            color: #6c757d;
            margin-top: 8px;
            text-align: center;
        }
        .step-item.active .step-label {
            color: #667eea;
            font-weight: 600;
        }
        .installer-body {
            padding: 40px;
        }
        .requirement-item {
            display: flex;
            align-items: center;
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 10px;
            background: #f8f9fa;
        }
        .requirement-icon {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-right: 15px;
            font-size: 1.2rem;
        }
        .requirement-success {
            background: #d4edda;
            color: #28a745;
        }
        .requirement-error {
            background: #f8d7da;
            color: #dc3545;
        }
        .progress-bar-animated {
            animation: progress-bar-stripes 1s linear infinite;
        }
        @keyframes progress-bar-stripes {
            from { background-position: 1rem 0; }
            to { background-position: 0 0; }
        }
    </style>
</head>
<body>
    <div class="installer-container">
        <div class="installer-card">
            <div class="installer-header">
                <h1><i class="bi bi-cloud-upload me-2"></i>PDF to Video Converter</h1>
                <p class="mb-0">Installation Wizard</p>
            </div>
            
            <div class="step-indicator">
                <div class="step-item <?php echo $step >= 1 ? 'active' : ''; ?> <?php echo $step > 1 ? 'completed' : ''; ?>">
                    <div class="step-number">1</div>
                    <div class="step-label">Requirements</div>
                </div>
                <div class="step-item <?php echo $step >= 2 ? 'active' : ''; ?> <?php echo $step > 2 ? 'completed' : ''; ?>">
                    <div class="step-number">2</div>
                    <div class="step-label">Database</div>
                </div>
                <div class="step-item <?php echo $step >= 3 ? 'active' : ''; ?> <?php echo $step > 3 ? 'completed' : ''; ?>">
                    <div class="step-number">3</div>
                    <div class="step-label">Configuration</div>
                </div>
                <div class="step-item <?php echo $step >= 4 ? 'active' : ''; ?>">
                    <div class="step-number">4</div>
                    <div class="step-label">Complete</div>
                </div>
            </div>
            
            <div class="installer-body">
                <?php if ($step === 1): ?>
                    <!-- Step 1: Requirements Check -->
                    <h3 class="mb-4"><i class="bi bi-check-circle me-2"></i>System Requirements</h3>
                    <p class="text-muted mb-4">We're checking if your server meets all the requirements.</p>
                    
                    <div id="requirements-check">
                        <div class="text-center py-5">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                            <p class="mt-3">Checking requirements...</p>
                        </div>
                    </div>
                    
                    <div id="requirements-result" style="display: none;">
                        <div id="requirements-list"></div>
                        
                        <div class="alert alert-info mt-4">
                            <i class="bi bi-info-circle me-2"></i>
                            <strong>Missing packages?</strong> Install them using:
                            <pre class="mt-2 mb-0 bg-white p-3 rounded"><code>sudo apt-get update
sudo apt-get install ffmpeg espeak poppler-utils php-gd php-mysqli</code></pre>
                        </div>
                        
                        <div class="d-flex justify-content-end mt-4">
                            <button id="recheck-btn" class="btn btn-outline-secondary me-2">
                                <i class="bi bi-arrow-clockwise me-1"></i>Recheck
                            </button>
                            <button id="proceed-step1" class="btn btn-primary" disabled>
                                Proceed <i class="bi bi-arrow-right ms-1"></i>
                            </button>
                        </div>
                    </div>
                    
                <?php elseif ($step === 2): ?>
                    <!-- Step 2: Database Configuration -->
                    <h3 class="mb-4"><i class="bi bi-database me-2"></i>Database Configuration</h3>
                    <p class="text-muted mb-4">Enter your database credentials. The database will be created automatically if it doesn't exist.</p>
                    
                    <form id="db-form">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="db_host" class="form-label">Database Host</label>
                                <input type="text" class="form-control" id="db_host" name="db_host" value="localhost" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="db_port" class="form-label">Database Port</label>
                                <input type="number" class="form-control" id="db_port" name="db_port" value="3306">
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="db_user" class="form-label">Database Username</label>
                                <input type="text" class="form-control" id="db_user" name="db_user" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="db_pass" class="form-label">Database Password</label>
                                <input type="password" class="form-control" id="db_pass" name="db_pass">
                            </div>
                        </div>
                        
                        <div class="mb-3">
                            <label for="db_name" class="form-label">Database Name</label>
                            <input type="text" class="form-control" id="db_name" name="db_name" value="pdf_to_video" required>
                            <div class="form-text">This database will be created automatically if it doesn't exist.</div>
                        </div>
                        
                        <div id="db-test-result" class="mb-3"></div>
                        
                        <div class="d-flex justify-content-between">
                            <a href="?step=1" class="btn btn-secondary">
                                <i class="bi bi-arrow-left me-1"></i>Back
                            </a>
                            <div>
                                <button type="button" id="test-db-btn" class="btn btn-outline-primary me-2">
                                    <i class="bi bi-wrench me-1"></i>Test Connection
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    Proceed <i class="bi bi-arrow-right ms-1"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    
                <?php elseif ($step === 3): ?>
                    <!-- Step 3: Final Configuration -->
                    <h3 class="mb-4"><i class="bi bi-gear me-2"></i>Final Configuration</h3>
                    <p class="text-muted mb-4">Configure your application settings.</p>
                    
                    <form id="config-form">
                        <div class="mb-3">
                            <label for="base_url" class="form-label">Base URL</label>
                            <input type="url" class="form-control" id="base_url" name="base_url" value="<?php echo htmlspecialchars($base_url_suggested); ?>" required>
                            <div class="form-text">The URL where your application will be accessible.</div>
                        </div>
                        
                        <div class="alert alert-warning">
                            <i class="bi bi-exclamation-triangle me-2"></i>
                            <strong>Important:</strong> After installation, please delete or rename <code>install.php</code> for security reasons.
                        </div>
                        
                        <div id="config-result" class="mb-3"></div>
                        
                        <div class="d-flex justify-content-between">
                            <a href="?step=2" class="btn btn-secondary">
                                <i class="bi bi-arrow-left me-1"></i>Back
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-check-circle me-1"></i>Complete Installation
                            </button>
                        </div>
                    </form>
                    
                <?php elseif ($step === 4): ?>
                    <!-- Step 4: Completion -->
                    <div class="text-center py-5">
                        <div class="mb-4">
                            <i class="bi bi-check-circle-fill text-success" style="font-size: 5rem;"></i>
                        </div>
                        <h2 class="mb-3">Installation Complete!</h2>
                        <p class="lead text-muted mb-4">Your PDF to Video Converter has been successfully installed.</p>
                        
                        <div class="card bg-light mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Next Steps:</h5>
                                <ol class="mb-0 text-start">
                                    <li>Delete or rename <code>install.php</code> for security</li>
                                    <li>Upload a PDF to test the conversion</li>
                                    <li>Customize settings in <code>includes/config.php</code></li>
                                </ol>
                            </div>
                        </div>
                        
                        <div class="d-flex justify-content-center gap-3">
                            <a href="index.php" class="btn btn-primary btn-lg">
                                <i class="bi bi-play-circle me-2"></i>Go to Application
                            </a>
                            <a href="my-videos.php" class="btn btn-outline-primary btn-lg">
                                <i class="bi bi-collection-play me-2"></i>View My Videos
                            </a>
                        </div>
                    </div>
                    
                <?php endif; ?>
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        <?php if ($step === 1): ?>
        // Step 1: Check requirements
        function checkRequirements() {
            fetch('install.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: 'action=check_requirements'
            })
            .then(response => response.json())
            .then(data => {
                const reqs = data.requirements;
                let html = '';
                let allPassed = true;
                
                const checks = [
                    { key: 'php_version', label: 'PHP 7.4+', icon: 'bi-filetype-php' },
                    { key: 'mysqli', label: 'MySQLi Extension', icon: 'bi-database' },
                    { key: 'gd', label: 'GD Library', icon: 'bi-image' },
                    { key: 'exec', label: 'exec() Function', icon: 'bi-terminal' },
                    { key: 'ffmpeg', label: 'FFmpeg', icon: 'bi-film' },
                    { key: 'espeak', label: 'eSpeak TTS', icon: 'bi-volume-up' },
                    { key: 'pdftotext', label: 'Poppler Utils (pdftotext)', icon: 'bi-file-earmark-pdf' }
                ];
                
                checks.forEach(check => {
                    const passed = reqs[check.key];
                    allPassed = allPassed && passed;
                    html += `
                        <div class="requirement-item ${passed ? '' : 'border border-danger'}">
                            <div class="requirement-icon ${passed ? 'requirement-success' : 'requirement-error'}">
                                <i class="bi ${passed ? 'bi-check-lg' : 'bi-x-lg'}"></i>
                            </div>
                            <div class="flex-grow-1">
                                <strong>${check.label}</strong>
                                <div class="small text-muted">${passed ? 'Installed' : 'Not found'}</div>
                            </div>
                            <i class="bi ${passed ? 'bi-check-circle-fill text-success' : 'bi-x-circle-fill text-danger'} fs-4"></i>
                        </div>
                    `;
                });
                
                document.getElementById('requirements-check').style.display = 'none';
                document.getElementById('requirements-result').style.display = 'block';
                document.getElementById('requirements-list').innerHTML = html;
                document.getElementById('proceed-step1').disabled = !allPassed;
                
                if (!allPassed) {
                    document.getElementById('proceed-step1').title = 'Please install missing requirements first';
                }
            })
            .catch(error => {
                console.error('Error:', error);
                document.getElementById('requirements-check').innerHTML = 
                    '<div class="alert alert-danger">Failed to check requirements. Please refresh the page.</div>';
            });
        }
        
        checkRequirements();
        
        document.getElementById('recheck-btn').addEventListener('click', function() {
            document.getElementById('requirements-check').style.display = 'block';
            document.getElementById('requirements-result').style.display = 'none';
            checkRequirements();
        });
        
        document.getElementById('proceed-step1').addEventListener('click', function() {
            window.location.href = '?step=2';
        });
        
        <?php elseif ($step === 2): ?>
        // Step 2: Database configuration
        document.getElementById('test-db-btn').addEventListener('click', function() {
            const formData = new FormData(document.getElementById('db-form'));
            formData.append('action', 'test_db');
            
            fetch('install.php', {
                method: 'POST',
                body: new URLSearchParams(formData)
            })
            .then(response => response.json())
            .then(data => {
                const resultDiv = document.getElementById('db-test-result');
                if (data.success) {
                    resultDiv.innerHTML = `<div class="alert alert-success"><i class="bi bi-check-circle me-2"></i>${data.message}</div>`;
                } else {
                    resultDiv.innerHTML = `<div class="alert alert-danger"><i class="bi bi-x-circle me-2"></i>${data.error}</div>`;
                }
            })
            .catch(error => {
                document.getElementById('db-test-result').innerHTML = 
                    '<div class="alert alert-danger">Connection test failed. Please check your credentials.</div>';
            });
        });
        
        document.getElementById('db-form').addEventListener('submit', function(e) {
            e.preventDefault();
            
            const formData = new FormData(this);
            formData.append('action', 'test_db');
            
            fetch('install.php', {
                method: 'POST',
                body: new URLSearchParams(formData)
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    // Save to session and proceed
                    sessionStorage.setItem('db_config', JSON.stringify({
                        db_host: document.getElementById('db_host').value,
                        db_user: document.getElementById('db_user').value,
                        db_pass: document.getElementById('db_pass').value,
                        db_name: document.getElementById('db_name').value
                    }));
                    window.location.href = '?step=3';
                } else {
                    document.getElementById('db-test-result').innerHTML = 
                        `<div class="alert alert-danger"><i class="bi bi-x-circle me-2"></i>${data.error}</div>`;
                }
            })
            .catch(error => {
                document.getElementById('db-test-result').innerHTML = 
                    '<div class="alert alert-danger">Connection test failed. Please check your credentials.</div>';
            });
        });
        
        <?php elseif ($step === 3): ?>
        // Step 3: Create configuration
        document.getElementById('config-form').addEventListener('submit', function(e) {
            e.preventDefault();
            
            const submitBtn = this.querySelector('button[type="submit"]');
            submitBtn.disabled = true;
            submitBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Creating configuration...';
            
            const formData = new FormData(this);
            formData.append('action', 'create_config');
            
            // Add DB credentials from session
            const dbConfig = JSON.parse(sessionStorage.getItem('db_config') || '{}');
            formData.append('db_host', dbConfig.db_host || 'localhost');
            formData.append('db_user', dbConfig.db_user || '');
            formData.append('db_pass', dbConfig.db_pass || '');
            formData.append('db_name', dbConfig.db_name || '');
            
            fetch('install.php', {
                method: 'POST',
                body: new URLSearchParams(formData)
            })
            .then(response => response.json())
            .then(data => {
                const resultDiv = document.getElementById('config-result');
                if (data.success) {
                    resultDiv.innerHTML = `<div class="alert alert-success"><i class="bi bi-check-circle me-2"></i>${data.message}</div>`;
                    
                    // Now create tables
                    return fetch('install.php', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                        },
                        body: 'action=create_tables'
                    });
                } else {
                    resultDiv.innerHTML = `<div class="alert alert-danger"><i class="bi bi-x-circle me-2"></i>${data.error}</div>`;
                    submitBtn.disabled = false;
                    submitBtn.innerHTML = '<i class="bi bi-check-circle me-1"></i>Complete Installation';
                    throw new Error('Config creation failed');
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    setTimeout(() => {
                        window.location.href = '?step=4';
                    }, 1500);
                } else {
                    document.getElementById('config-result').innerHTML = 
                        `<div class="alert alert-danger"><i class="bi bi-x-circle me-2"></i>${data.error}</div>`;
                    submitBtn.disabled = false;
                    submitBtn.innerHTML = '<i class="bi bi-check-circle me-1"></i>Complete Installation';
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });
        <?php endif; ?>
    });
    </script>
</body>
</html>
